### ISSUE TITLE
Hvor ligger bannere og hvordan endres disse?

### ISSUE THREAD

**Issue by kjetilsortun** [askoyfk/askoyfk.github.io#45]

**Comment by batfink** [comment]
Ser du fant ut av det :+1:  Planen er å lage en egen npm-modul for bannere, men vi er ikke helt der ennå. Men jeg ser du også slettet innkalling til årsmøtet fra nyheter, var det hensikten? For det jeg tenkte var at når vi hadde litt nyheter etter en stund, eller når vi får flyttet over de gamle, så kunne vi lagt inn en link til nyheter i hovednavigasjonen: http://www.askoyfk.no/nyheter/

Vi burde gjerne tatt oss en prat om strukturen på sidene. Har du tid til et lite videomøte på f.eks. https://appear.in/askoyfk i kveld? Du trenger i utgangspunktet ikke noe plugin eller konto, med mindre du har behov for å dele skjermen din – da tror jeg du må installere en plugin i Chrome hvis jeg ikke husker feil.

**Comment by kjetilsortun** [comment]
Løste problemet mitt i går :-), men vi trenger et arkiv ja, så vi kan hente tilbake fra historikken og flytte til gamle bannere og får opp en enkel struktur rundt årshjulet...

De neste tre dagene har jeg litt mange kveldsaktiviteter, men skal på foreldre møtet torsdag, så vi kan ta 3 minutter da og avtale et tidspunkt for videre utvikling av sidene.. Tror det skal fungere greit :+1: 

K
